### ISSUE TITLE
Meteor crash if others packages want to handle .json file

### ISSUE THREAD

**Issue by atoy40** [Differential/meteor-vulcanize#15]
Hello,

To handle vulcanize.json file, you added a ".json" source handler. It is a problem if you want to use it with other package handling a .json file too (for example mquandalle:bower which handle bower.json)
mquandalle:bower use a little trick (https://github.com/mquandalle/meteor-bower/blob/master/plugin/handler.js#L212) but it becomes with his problems too (you cannot register two times json extention for example, so you cannot use the trick in more than one package).

the meteor registerBuildPlugin() function is - as documented - waiting for extentions, not filename, so what do you think of using a specific extention (.vulcanize or any...) ? it can removed all problems.

Anthony.

**Comment by schnie** [comment]
Gotcha, yea I used to be able to watch for "imports.html", but wasn't able
to watch "vulcanize.json", so I opted to just watch for ".json" and filter
for the one we cared bout.  I'm fine with changing it to watch for
".vulcanize".

On Wed, Jun 17, 2015 at 9:20 AM, Anthony Hinsinger <notifications@github.com

**Comment by atoy40** [comment]
Yes, you've been able to do it with imports.html because meteor already define a html handler (this is the bower package trick)

**Comment by atoy40** [comment]
May be it's a good idea to have a handler for vulcanize extention, but continue to filter for a specific filename (config.vulcanize ?) to avoid a user to use two .vulcanize file in the app tree ?
