### ISSUE TITLE
Unexprected token

### ISSUE THREAD

**Issue by Unavi** [Differential/meteor-vulcanize#22]
When I run the project with the standard config:

    {
        "polyfill": "/bower_components/webcomponentsjs/webcomponents.min.js",
        "useShadowDom": true, // optional, defaults to shady dom (polymer default)
        "imports": [
            "/bower_components/paper-button/paper-button.html",
            "/bower_components/paper-checkbox/paper-checkbox.html"
        ]
    }
I get this:

    => Started proxy.
    => Started MongoDB.
    => Errors prevented startup:
       While building the application:
       native: Unexpected token / (compiling config.vulcanize)
       at Object.parse (native)
       at Package (packages/vulcanize/vulcanize.js:118:1)

The paths are right and when I do it by hand with the vulcanize command line it works.
Any idea why it's not working?

**Comment by schnie** [comment]
What happens if you remove the comment on the `useShadowDom` line?

**Comment by Unavi** [comment]
You are the man, the myth, the legend. :smile:
I slowly grew desperate trying to add it with bower myself^^

Made my day^^
