### ISSUE TITLE
Meteor 1.2 Compatibility 

### ISSUE THREAD

**Issue by ThaumRystra** [Differential/meteor-vulcanize#24]
In all my projects that use vulcanize, when upgrading to Meteor 1.2 headers are no longer included, breaking all Polymer elements. This happens whether VULCANIZE=true or not.

**Comment by schnie** [comment]
I haven't had a chance to upgrade yet but will look at this when I do.
Until then, I'll gladly accept a PR if you want to take a crack at it!

**Comment by SylarRuby** [comment]
I'm preventing from opening up another issue as I suspect an issue with meteor 1.2. My issue is: `Uncaught TypeError: Polymer is not a function`

**Comment by xalgorithm** [comment]
I'm having some of the same issues. I am unable to get polymer and meteor to work together after upgrading to meteor 1.2.1. I tried @ThaumRystra 's instructions is his 
https://github.com/Differential/meteor-vulcanize/issues/25, but I get an error there also.

I'll probably have to change over from polymer for the front end, and that's kind of disappointing.
Great work so far, I hope this gets fixed.

**Comment by ThaumRystra** [comment]
> but I get an error there also.

@xalgorithm What error are you getting? When you build or in the client?

**Comment by xalgorithm** [comment]
I've ensured that I'm using your alternative patched branch.
```
....

check                       1.1.0  Check whether a value matches a pattern
coffeescript                1.0.11  Javascript dialect with fewer braces and semicolons
_differential:vulcanize     2.0.1+ Vulcanize_
ejson                       1.0.7  Extended and Extensible JSON library
insecure                    1.0.4  (For prototyping only) Allow all database writes from the client
iron:router                 1.0.12  Routing specifically designed for Meteor
...

+ These packages are built locally from source.
```
My error:
```
While processing files with templating (for target web.browser):
   client/templates/layout/imports.html:2: Expected one of: <body>, <head>, <template>

   While processing files with templating (for target web.cordova):
   client/templates/layout/imports.html:2: Expected one of: <body>, <head>, <template>

=> Your application has errors. Waiting for file change.

```
The Repo and Branch: https://github.com/SLACNationalAcceleratorLaboratory/data-center-sensors/tree/polymer-interface

**Comment by xalgorithm** [comment]
Also, thanks for any assistance. It is much appreciated. I am no Meteor expert and I'm piecing how all of this works from docs and stack exchange.

**Comment by ThaumRystra** [comment]
As of version 1.0 vulcanize uses a `config.vulcanize` file, not `imports.html`. Check the [readme](https://github.com/Differential/meteor-vulcanize/blob/master/README.md) for details on how to set it up.

**Comment by patriceleva** [comment]
Hello, 
Sorry i have problem with the config.vulcanize.
The file vulcanize-...html is not generated.
I use meteor 1.2.1 and polymer 1.2.1.
Can you see the problem plz :)

**Comment by patriceleva** [comment]
this is my config :
config.vulcanize:
{
  "polyfill": "/bower_components/webcomponentsjs/webcomponents-lite.min.js",
  "useShadowDom": false,
  "imports": [
          "/bower_components/google-map/google-map.html",
          "/bower_components/google-map/google-map-marker.html",
          "/bower_components/google-map/google-map-directions.html",
          "/components/component-index/component-index.html",
          "/components/bar-chart/bar-chart.html"
      ]
}

and my packages : 
D:\staf\TestGitHub\testIronMeteor\app>meteor list
blaze-html-templates    1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
check                   1.1.0  Check whether a value matches a pattern
d3                      1.0.0  Library for manipulating documents based on data
differential:vulcanize  2.0.1  Vulcanize
ejson                   1.0.7  Extended and Extensible JSON library
force-ssl               1.0.6  Require this application to use HTTPS
insecure                1.0.4  (For prototyping only) Allow all database writes from the client
iron:router             1.0.12  Routing specifically designed for Meteor
jquery                  1.11.4  Manipulate the DOM using CSS selectors
logging                 1.0.8  Logging facility.
mdg:geolocation         1.1.0  Provides reactive geolocation on desktop and mobile.
meteor-base             1.0.1  Packages that every Meteor app needs
mobile-experience       1.0.1  Packages for a great mobile user experience
mongo                   1.1.3  Adaptor for using MongoDB and Minimongo over DDP
random                  1.0.5  Random number generator and utilities
reload                  1.1.4  Reload the page while preserving application state.
session                 1.1.1  Session variable
spacebars               1.0.7  Handlebars-like template language for Meteor
standard-minifiers      1.0.2  Standard minifiers used with Meteor apps by default.
tracker                 1.0.9  Dependency tracker to allow reactive callbacks



"C:\Program Files (x86)\JetBrains\WebStorm 9.0.2\bin\runnerw.exe" C:\Users\insit05\AppData\Local\.meteor\meteor.bat
[[[[[ ~\D\staf\TestGitHub\testIronMeteor\app ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Vulcanize: Importing vulcanized file...
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.



and the html generated : 

<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/merged-stylesheets.css?6be5f0d26dfb744e9e66434f9b114fe3b022de4f">


<script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.2.1%22%2C%22PUBLIC_SETTINGS%22%3A%7B%7D%2C%22ROOT_URL%22%3A%22http%3A%2F%2Flocalhost%3A3000%2F%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22appId%22%3A%221cg0qppf7abmh1twvtx0%22%2C%22autoupdateVersion%22%3A%22fee65bf42b90175381356fb291418b0783463eca%22%2C%22autoupdateVersionRefreshable%22%3A%22c4dbe3d67edd45b0ff9dce9b3b7deba6b1cf632e%22%2C%22autoupdateVersionCordova%22%3A%22none%22%7D"));</script>

  <script type="text/javascript" src="/packages/underscore.js?46eaedbdeb6e71c82af1b16f51c7da4127d6f285"></script>
  <script type="text/javascript" src="/packages/meteor.js?9730f4ff059088b3f7f14c0672d155218a1802d4"></script>
  <script type="text/javascript" src="/packages/insecure.js?e7411f6cee07c76688e26c3b20767e857b42ad9f"></script>
  <script type="text/javascript" src="/packages/tracker.js?7776276660c988c38fed448d8262b925dffb5bc3"></script>
  <script type="text/javascript" src="/packages/deps.js?a0f1fc18309813a3aac8954f76d0c73e4c5d46f4"></script>
  <script type="text/javascript" src="/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357"></script>
  <script type="text/javascript" src="/packages/base64.js?6b407c3b106cfc043cc07a07a111a2443d789bd4"></script>
  <script type="text/javascript" src="/packages/ejson.js?5e95dd4b5971d96cb2d3287c54b14d9002f83ab7"></script>
  <script type="text/javascript" src="/packages/check.js?9c4972d3f4fe56cd455d3022e70b5195e642fc41"></script>
  <script type="text/javascript" src="/packages/htmljs.js?fd1566f5a5a4b277eb93f0a636a84a07ab9a83db"></script>
  <script type="text/javascript" src="/packages/id-map.js?c9a0833f370b91bbc3fd76d54f21d6ce1850af49"></script>
  <script type="text/javascript" src="/packages/babel-compiler.js?b72b25550ee1619b0eaddf5e0c1541e8c264ccf0"></script>
  <script type="text/javascript" src="/packages/ecmascript.js?9c79b20dd3f3a6da85828defdd8585b8436af75d"></script>
  <script type="text/javascript" src="/packages/babel-runtime.js?b0359ff15b87202234ffb6a78f85b70175b412af"></script>
  <script type="text/javascript" src="/packages/ecmascript-runtime.js?d552d50ef9d63d143f8f549245241748a4796cec"></script>
  <script type="text/javascript" src="/packages/promise.js?c18eac25a2117745aa5b372e139bae2fce4a84fe"></script>
  <script type="text/javascript" src="/packages/random.js?5851416a296763029b1a4d7302fb9dc24aba51d2"></script>
  <script type="text/javascript" src="/packages/mongo-id.js?3c6c0f6ceace5f42b7dfee0fcafe19ae1b711909"></script>
  <script type="text/javascript" src="/packages/diff-sequence.js?f4337773c8aaf9bcaa5f5f22865660cbdd471eaa"></script>
  <script type="text/javascript" src="/packages/observe-sequence.js?cd318009bd759e1458173f84a537c5dd315b4f86"></script>
  <script type="text/javascript" src="/packages/reactive-var.js?975c4d5513ecf8c3a212b5aa160a9ea4447f3079"></script>
  <script type="text/javascript" src="/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9"></script>
  <script type="text/javascript" src="/packages/ui.js?6aa94fb4743be2472f799f928674607edae2afdf"></script>
  <script type="text/javascript" src="/packages/spacebars.js?1aedcc2aa3ae9ff5d860d73516110cedd77c033e"></script>
  <script type="text/javascript" src="/packages/templating.js?d7be2bab3c1e28f0cd14c87f8d52857a34311d16"></script>
  <script type="text/javascript" src="/packages/iron_core.js?b2f68eb0ae5bdc20eb7fd90373d995fe1908b980"></script>
  <script type="text/javascript" src="/packages/iron_dynamic-template.js?ebc5266f87a0be7618b1f690df32f1aa90ec89d7"></script>
  <script type="text/javascript" src="/packages/iron_layout.js?9b12927a3224ccc6cd071e832e37aa4f11b83992"></script>
  <script type="text/javascript" src="/packages/iron_url.js?410da9bf2fb4b7ccf789a68539abfc6f1b8bd55a"></script>
  <script type="text/javascript" src="/packages/iron_middleware-stack.js?3370bd57ef7b310cca3f5dddb11b77fafdcfc1eb"></script>
  <script type="text/javascript" src="/packages/iron_location.js?a504b662036fee426fee61c89a00913fec9a3ef4"></script>
  <script type="text/javascript" src="/packages/ordered-dict.js?18a4254f3dd5f8c97946dadb60e33c91efab39c1"></script>
  <script type="text/javascript" src="/packages/geojson-utils.js?bfbab9d995bbbb19fa1b11a3cfdb9da5f5f328ba"></script>
  <script type="text/javascript" src="/packages/minimongo.js?cdf1a26cf7719fa9471a8017c3defd5aea812727"></script>
  <script type="text/javascript" src="/packages/retry.js?acb5f93adc31a57311c18af4ce21068297f00f37"></script>
  <script type="text/javascript" src="/packages/ddp-common.js?5bfbe93c6ad5580f8d13f28d81b2c0db0dae13c4"></script>
  <script type="text/javascript" src="/packages/reload.js?234f78ebae6ce49cbb0da4705afaec398706283b"></script>
  <script type="text/javascript" src="/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f"></script>
  <script type="text/javascript" src="/packages/ddp.js?1c935134013739ed5ece46880dea800b6319bd67"></script>
  <script type="text/javascript" src="/packages/ddp-server.js?1057b33d71942bc01fd0167e2b2a5f49f5545d11"></script>
  <script type="text/javascript" src="/packages/mongo.js?69942a86515ec397dfd8cbb0a151a0eefdd9560d"></script>
  <script type="text/javascript" src="/packages/reactive-dict.js?8210a4b2fa52dbde9b3c8cf6b296192a34d7b899"></script>
  <script type="text/javascript" src="/packages/iron_controller.js?20327f0adf618028f4e33ee2fc6d6af85b26fc9f"></script>
  <script type="text/javascript" src="/packages/iron_router.js?c564289eeaa191561eba900052037432ebfcbe4a"></script>
  <script type="text/javascript" src="/packages/force-ssl.js?d23ea88be231ffe319745611da07a34c03ba3354"></script>
  <script type="text/javascript" src="/packages/mdg_geolocation.js?eb36591b0ff75b4a46cc9b85da7ce8b4ad46b42e"></script>
  <script type="text/javascript" src="/packages/d3.js?c2239ebc4f27d45a5de38abb6b9a7ac56a065773"></script>
  <script type="text/javascript" src="/packages/standard-minifiers.js?b02a7937678c6058031ee7b2f45b5a617518335d"></script>
  <script type="text/javascript" src="/packages/meteor-base.js?f0836ed3757e6217fff6e2710a1293407a6d9b09"></script>
  <script type="text/javascript" src="/packages/mobile-experience.js?674f55574f9947b91bb5f92f9ea9be098479b649"></script>
  <script type="text/javascript" src="/packages/blaze-html-templates.js?31453f3129c01ec6fabaa5b791f6572e8c4464a2"></script>
  <script type="text/javascript" src="/packages/session.js?9a40cf46e8dc125a3486dc33b2a965c1e9f8ff2b"></script>
  <script type="text/javascript" src="/packages/logging.js?3b4580b6acbb8447ac412aad2cafc2f7df3b2435"></script>
  <script type="text/javascript" src="/packages/differential_vulcanize.js?670fe3e91d955a61aca86e18009b8f25c5ad9cbc"></script>
  <script type="text/javascript" src="/packages/webapp.js?1b9f36d855fc5c8399abf2579ac1e1512060cc95"></script>
  <script type="text/javascript" src="/packages/livedata.js?93f27626c1702ea8af804d6170ffbf8968626718"></script>
  <script type="text/javascript" src="/packages/hot-code-push.js?3916ae26c3ca4928e61dc2da7e7b3f93e4164c0c"></script>
  <script type="text/javascript" src="/packages/launch-screen.js?b50bb1bd905d2cc3d6182ee28c096df0cc24a725"></script>
  <script type="text/javascript" src="/packages/autoupdate.js?764e166739a4aeba204926326b786baa4292b65d"></script>
  <script type="text/javascript" src="/packages/global-imports.js?25c661cf0f2e1b388caa847f564837d9d405a130"></script>
  <script type="text/javascript" src="/app/client/templates/layouts/master_layout/template.master_layout.js?971074b5a23f7960a14fedb6c9babd2f0f4312c5"></script>
  <script type="text/javascript" src="/app/client/templates/shared/loading/template.loading.js?5c1607028e140b94e0ac75d6c1ad8b157cb79d68"></script>
  <script type="text/javascript" src="/app/client/templates/shared/not_found/template.not_found.js?628f7486c33700ee75e736ab5af3a4b43f3732f7"></script>
  <script type="text/javascript" src="/app/client/templates/home/template.home.js?c2471e5741dc69738a3a019f007af0e2d5d80033"></script>
  <script type="text/javascript" src="/app/client/templates/home/template.page1.js?23dc3279dc71fa988bb5509a9058a3f5c37aa5ab"></script>
  <script type="text/javascript" src="/app/client/templates/home/template.page2.js?fc7f0220e75039902c5840de9bd9f65117d631b9"></script>
  <script type="text/javascript" src="/app/lib/controllers/home_controller.js?b5f660bc40c691750ba490e8cf1cc8671aaef1ab"></script>
  <script type="text/javascript" src="/app/lib/controllers/page1_controller.js?20d081b359cc8d6a294cda67e3dabf13155585c7"></script>
  <script type="text/javascript" src="/app/lib/controllers/page2_controller.js?bdfdb2a990b99e3f8760e85c2671939e3348b83c"></script>
  <script type="text/javascript" src="/app/lib/methods.js?63d6bf4cbd6e227a2e63f92746979e62c429d1bc"></script>
  <script type="text/javascript" src="/app/lib/routes.js?1d31a720cbb2793a5293c59126eb1b792d7ffd83"></script>
  <script type="text/javascript" src="/app/client/templates/layouts/master_layout/master_layout.js?ac81f55dc2f121ca1990ccdb337fc7a4d8002a97"></script>
  <script type="text/javascript" src="/app/client/templates/custom/CustomHelpers.js?29a9708063d54ec6406c5f9b0035e7d811e21020"></script>
  <script type="text/javascript" src="/app/client/templates/home/home.js?f066c3fb3b7be59edfbead4b77c1f0e27d108667"></script>
  <script type="text/javascript" src="/app/client/templates/home/page1.js?1c373623fd56a750f90870f6ccbe06e3a19412f0"></script>
  <script type="text/javascript" src="/app/client/templates/home/page2.js?60be25a1dffc0e5da6754bd22894a858d0740665"></script>


<meta charset="utf-8">
    <title>testIronProject</title>
    <meta name="description" content="testIronProject">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1, user-scalable=yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
<script src="/bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>

</head>
<body>
</body>
</html>


Thx a lot :)

LP

**Comment by xalgorithm** [comment]
That solved it, thank you.
I've pulled Polymer 5 and just added the base polymer 1.0 package.
I'll try and reconstruct from there.
