### ISSUE TITLE
Add Readme on Atmosphere

### ISSUE THREAD

**Issue by jadsonlourenco** [Differential/meteor-vulcanize#4]
After 100+ downloads, 10+ stars on Atmosphere is good for this package have a **readme** to explain more about. (https://atmospherejs.com/differential/vulcanize)

Thank you for this package is really good!

**Comment by schnie** [comment]
Good call!  Done

**Comment by jadsonlourenco** [comment]
Thanks man, and I get this working, thank you so much.
