### ISSUE TITLE
import.html: bad formatting error

### ISSUE THREAD

**Issue by lorensr** [Differential/meteor-vulcanize#5]
Hi, I see that the `import.html` works in `polymer-demo`, but when I add `vulcanize` to my project and use the same `import.html` file that the demo uses, I get:

```
=> Errors prevented startup:                  
   
   While building the application:
   client/views/import.html:2: bad formatting in HTML template
```

Because all of the `<link rel="import" href="/components/*.html">` tags aren't inside a `<template>` or `<head>` tag. How do I fix this? Thanks!

**Comment by schnie** [comment]
None of our apps have had this issue yet, so it's hard to say.  What
version of meteor and polymer are you using?  Can you provide a sample
app?  Thanks!

**Comment by CharleneMolino** [comment]
Sure, I made one here:

https://github.com/lorensr/vulcanize-issue5

```
bower install
meteor
```

Version 1.0.2.1. I feel like there should be some way to tell vulcanize which file to parse and hide from Meteor?

**Comment by lorensr** [comment]
Sure, I made one here:

https://github.com/lorensr/vulcanize-issue5

```
bower install
meteor
```

Version 1.0.2.1. I feel like there should be some way to tell vulcanize which file to parse and hide from Meteor?

**Comment by schnie** [comment]
Thanks man.  The example repo does not have `differential:vulcanize` in its pacakge list.  I assume your real application has this added though.  The real issue is that the file is named `import.html` when it should be `imports.html`, with an s.  Hope that fixes it, let me know if you are still getting the error.

**Comment by lorensr** [comment]
Haha thank you, fixed.

**Comment by pashadee** [comment]
Not sure if you still follow this thread but I'm having the same issue as described above, my file is called imports.html and I have differential:vulcanize installed
Meteor 1.1.0.3
Polymer 1.1.0
vulcanize: 2.0.1

Any ideas would be appreciated!

**Comment by jorgekarv** [comment]
I had the same problem, i solved using the same vulcanize version as the sample code:
1) meteor remove differencial:vulcanize
2) meteor add  differential:vulcanize@0.0.3
